version: '3'
services:

  db:
    image: postgres
    restart: always
    ports:
      - "35432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=mails_db
  mail:
    container_name: fake-smtp-server
    image: gessnerfl/fake-smtp-server:latest
    restart: always
    ports:
      - "5025:5025"
      - "5080:5080"
      - "5081:5081"
    environment:
      FAKESMTP_AUTHENTICATION_USERNAME: username
      FAKESMTP_AUTHENTICATION_PASSWORD: password

  rabbitmq:
    container_name: rabbitmq-message-service
    image: 'rabbitmq:management'
    ports:
      - "5672:5672"
      - "15672:15672"